services:
  # api:
  #   container_name: api
  #   image: node:20
  #   ports:
  #     - ${PORT}:${PORT}
  #   depends_on:
  #     - db
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   stdin_open: true 
  #   tty: true
  #   env_file:
  #    - .env

  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - '${DB_HOST_PORT}:${DB_PORT}'
    volumes:
      - postgresdb3:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=America/Sao_Paulo
    env_file:
      - .env


  db_test:
    env_file: 
      - .env
    container_name: test_postgres
    image: postgres:latest
    volumes:
      - postgresdbtest:/var/lib/postgresql/data
    ports:
      - '${TEST_DB_HOST_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASS}
      - POSTGRES_DB=${TEST_DB_NAME}
    


volumes:
  postgresdb3:
  postgresdbtest: